name: Main workflow
on:
  push:
    branches:
      - main
env:
  WORKSPACE: ${{ vars.WORKSPACE_PROD }}

jobs:
  build:
    name: Build and Deploy
    runs-on: 
      labels: ["self-hosted", "data-pipeline"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $WORKSPACE, so your job can access it
      - name: Checkout repository
        run: |
          cd $WORKSPACE/${{ vars.PROJECT_NAME }}
          git config credential.helper '!f() { sleep 1; echo "username=${{ secrets.GH_USER }}"; echo "password=${{ secrets.GH_TOKEN }}"; }; f'
          git checkout main
          git pull

      - name: Build new image
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd $WORKSPACE/
          docker compose build --build-arg GH_TOKEN=$GH_TOKEN --build-arg GH_USER=$GH_USER ${{ vars.PROJECT_NAME }} 

      - name: Rollout new image
        run: |
          cd $WORKSPACE/
          docker compose up -d ${{ vars.PROJECT_NAME }}
